version: '3'
services:
  server:
    build: server
    ports:
      - "80:80"
    depends_on:
      - mysql-service

  front:
    build: front
    ports:
      - "8080:80"
    depends_on:
      - server

  mysql-service:
    image: mysql:5.7
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inquiry
      MYSQL_USER: main
      MYSQL_PASSWORD: password
