version: '3'
services:
  server:
    build: server
    container_name: inquiry_server
    ports:
      - "8080:80"
    depends_on:
      - db

  front:
    build: front
    container_name: inquiry_front
    ports:
      - "8081:80"
    depends_on:
      - server
  
  db:
    image: mysql
    container_name: inquiry_mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inquiry
      MYSQL_USER: go
      MYSQL_PASSWORD: password
