apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: inquiry-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            backend:
              serviceName: server-service
              servicePort: 80
          - path: /
            backend:
              serviceName: front-service
              servicePort: 80
